//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] alart {
            get {
                object obj = ResourceManager.GetObject("alart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] b {
            get {
                object obj = ResourceManager.GetObject("b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] c {
            get {
                object obj = ResourceManager.GetObject("c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [config]
        ///SpeakUnknowSystem=1
        ///SkipTrade=1
        ///TradeKeyWords=[多件物品],集结点,出售,频道更换
        ///DebugMessage=0.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        public static byte[] d {
            get {
                object obj = ResourceManager.GetObject("d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] e {
            get {
                object obj = ResourceManager.GetObject("e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] enemy {
            get {
                object obj = ResourceManager.GetObject("enemy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] f {
            get {
                object obj = ResourceManager.GetObject("f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] g {
            get {
                object obj = ResourceManager.GetObject("g", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] gang {
            get {
                object obj = ResourceManager.GetObject("gang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] h {
            get {
                object obj = ResourceManager.GetObject("h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] i {
            get {
                object obj = ResourceManager.GetObject("i", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] j {
            get {
                object obj = ResourceManager.GetObject("j", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] k {
            get {
                object obj = ResourceManager.GetObject("k", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] l {
            get {
                object obj = ResourceManager.GetObject("l", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] m {
            get {
                object obj = ResourceManager.GetObject("m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] manyred {
            get {
                object obj = ResourceManager.GetObject("manyred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] n {
            get {
                object obj = ResourceManager.GetObject("n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] o {
            get {
                object obj = ResourceManager.GetObject("o", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] p {
            get {
                object obj = ResourceManager.GetObject("p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] q {
            get {
                object obj = ResourceManager.GetObject("q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] r {
            get {
                object obj = ResourceManager.GetObject("r", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] s {
            get {
                object obj = ResourceManager.GetObject("s", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] t {
            get {
                object obj = ResourceManager.GetObject("t", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] u {
            get {
                object obj = ResourceManager.GetObject("u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] v {
            get {
                object obj = ResourceManager.GetObject("v", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] w {
            get {
                object obj = ResourceManager.GetObject("w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] y {
            get {
                object obj = ResourceManager.GetObject("y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] z {
            get {
                object obj = ResourceManager.GetObject("z", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
